version: "2"
services:
  boxer:
    image: mrbl4cyk/boxer:1.0
    container_name: boxer_core
    depends_on:
      - redis
    volumes:
      - ./db:/var/www/django_app/db
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      - ./uploads:/var/www/django_app/uploads
    ports:
      - "80:80"
    links:
      - redis
    restart: always
  redis:
    image: redis:latest
    container_name: boxer_redis
    expose:
      - "6379"
    restart: always
