version: "2"
services:
  boxer:
    build: .
    container_name: boxer01
    depends_on:
      - redis
    volumes:
      - ./db:/var/www/django_app/db
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      - ./uploads:/var/www/django_app/uploads
    ports:
      - "80:80"
    links:
      - redis
  redis:
    image: redis:latest
    container_name: redis01
    expose:
      - "6379"